export const SET_RECIPE = {
  REQ_RECIPE: "REQ_RECIPE",
  REQ_RECIPE_SUCCESS: "REQ_RECIPE_SUCCESS",
  REQ_RECIPE_FAIL: "REQ_RECIPE_FAIL",

  REQ_DELTE_RECIPE_SUCCESS: "REQ_DELTE_RECIPE_SUCCESS",
  REQ_DELTE_RECIPE_FAIL: "REQ_DELTE_RECIPE_FAIL",

  FILTER_RECIPE_SUCCESS: "FILTER_RECIPE_SUCCESS",
  FILTER_RECIPE_FAIL: "FILTER_RECIPE_FAIL",
};